/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAffirmationsRouteImport } from './routes/_authenticated/affirmations'
import { Route as AuthenticatedBadgesRouteImport } from './routes/_authenticated/badges'
import { Route as AuthenticatedChangeEmailRouteImport } from './routes/_authenticated/change-email'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedCheckInRouteImport } from './routes/_authenticated/check-in'
import { Route as AuthenticatedDailyExerciseRouteImport } from './routes/_authenticated/daily-exercise'
import { Route as AuthenticatedFlagsRouteImport } from './routes/_authenticated/flags'
import { Route as AuthenticatedHealingToolsRouteImport } from './routes/_authenticated/healing-tools'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedLettersRouteImport } from './routes/_authenticated/letters'
import { Route as AuthenticatedMoodAnalyticsRouteImport } from './routes/_authenticated/mood-analytics'
import { Route as AuthenticatedPicturesRouteImport } from './routes/_authenticated/pictures'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedQuestionnaireRouteImport } from './routes/_authenticated/questionnaire'
import { Route as AuthenticatedRitualsRouteImport } from './routes/_authenticated/rituals'
import { Route as AuthenticatedStreakUnlockRouteImport } from './routes/_authenticated/streak-unlock'
import { Route as AuthenticatedSubmitBugRouteImport } from './routes/_authenticated/submit-bug'
import { Route as AuthenticatedTriggersRouteImport } from './routes/_authenticated/triggers'
import { Route as AuthenticatedWinsRouteImport } from './routes/_authenticated/wins'
import { Route as AuthenticatedMotivationIndexRouteImport } from './routes/_authenticated/motivation/index'
import { Route as AuthenticatedMotivationTopicIdRouteImport } from './routes/_authenticated/motivation/$topicId'
import { Route as AuthenticatedMotivationAlcoholControlRouteImport } from './routes/_authenticated/motivation/alcohol-control'
import { Route as AuthenticatedMotivationGratitudeJarRouteImport } from './routes/_authenticated/motivation/gratitude-jar'
import { Route as AuthenticatedMotivationGuideRouteImport } from './routes/_authenticated/motivation/guide'
import { Route as AuthenticatedMotivationJourneyRouteImport } from './routes/_authenticated/motivation/journey'
import { Route as AuthenticatedMotivationMeditationRouteImport } from './routes/_authenticated/motivation/meditation'
import { Route as AuthenticatedMotivationWalkRouteImport } from './routes/_authenticated/motivation/walk'
import { Route as AuthenticatedMotivationWorryBoxRouteImport } from './routes/_authenticated/motivation/worry-box'
import { Route as ApiPublicDriveRouteImport } from './routes/api/public/drive'
import { Route as ApiPublicProTrialRouteImport } from './routes/api/public/pro-trial'
import { Route as OauthGoogleDriveReturnRouteImport } from './routes/oauth/google-drive/return'
import { Route as AuthenticatedMotivationHealingAudioIndexRouteImport } from './routes/_authenticated/motivation/healing-audio/index'
import { Route as AuthenticatedMotivationHealingAudioCategoryIdRouteImport } from './routes/_authenticated/motivation/healing-audio/$categoryId'
import { Route as ApiPublicHooksPushSchedulerRouteImport } from './routes/api/public/hooks/push-scheduler'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffirmationsRoute =
  AuthenticatedAffirmationsRouteImport.update({
    id: '/affirmations',
    path: '/affirmations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBadgesRoute = AuthenticatedBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangeEmailRoute =
  AuthenticatedChangeEmailRouteImport.update({
    id: '/change-email',
    path: '/change-email',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckInRoute = AuthenticatedCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyExerciseRoute =
  AuthenticatedDailyExerciseRouteImport.update({
    id: '/daily-exercise',
    path: '/daily-exercise',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFlagsRoute = AuthenticatedFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealingToolsRoute =
  AuthenticatedHealingToolsRouteImport.update({
    id: '/healing-tools',
    path: '/healing-tools',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLettersRoute = AuthenticatedLettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoodAnalyticsRoute =
  AuthenticatedMoodAnalyticsRouteImport.update({
    id: '/mood-analytics',
    path: '/mood-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPicturesRoute = AuthenticatedPicturesRouteImport.update({
  id: '/pictures',
  path: '/pictures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionnaireRoute =
  AuthenticatedQuestionnaireRouteImport.update({
    id: '/questionnaire',
    path: '/questionnaire',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRitualsRoute = AuthenticatedRitualsRouteImport.update({
  id: '/rituals',
  path: '/rituals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStreakUnlockRoute =
  AuthenticatedStreakUnlockRouteImport.update({
    id: '/streak-unlock',
    path: '/streak-unlock',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmitBugRoute = AuthenticatedSubmitBugRouteImport.update({
  id: '/submit-bug',
  path: '/submit-bug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTriggersRoute = AuthenticatedTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWinsRoute = AuthenticatedWinsRouteImport.update({
  id: '/wins',
  path: '/wins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotivationIndexRoute =
  AuthenticatedMotivationIndexRouteImport.update({
    id: '/motivation/',
    path: '/motivation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotivationTopicIdRoute =
  AuthenticatedMotivationTopicIdRouteImport.update({
    id: '/motivation/$topicId',
    path: '/motivation/$topicId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotivationAlcoholControlRoute =
  AuthenticatedMotivationAlcoholControlRouteImport.update({
    id: '/motivation/alcohol-control',
    path: '/motivation/alcohol-control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotivationGratitudeJarRoute =
  AuthenticatedMotivationGratitudeJarRouteImport.update({
    id: '/motivation/gratitude-jar',
    path: '/motivation/gratitude-jar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotivationGuideRoute =
  AuthenticatedMotivationGuideRouteImport.update({
    id: '/motivation/guide',
    path: '/motivation/guide',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotivationJourneyRoute =
  AuthenticatedMotivationJourneyRouteImport.update({
    id: '/motivation/journey',
    path: '/motivation/journey',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotivationMeditationRoute =
  AuthenticatedMotivationMeditationRouteImport.update({
    id: '/motivation/meditation',
    path: '/motivation/meditation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotivationWalkRoute =
  AuthenticatedMotivationWalkRouteImport.update({
    id: '/motivation/walk',
    path: '/motivation/walk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotivationWorryBoxRoute =
  AuthenticatedMotivationWorryBoxRouteImport.update({
    id: '/motivation/worry-box',
    path: '/motivation/worry-box',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDriveRoute = ApiPublicDriveRouteImport.update({
  id: '/api/public/drive',
  path: '/api/public/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProTrialRoute = ApiPublicProTrialRouteImport.update({
  id: '/api/public/pro-trial',
  path: '/api/public/pro-trial',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleDriveReturnRoute = OauthGoogleDriveReturnRouteImport.update({
  id: '/oauth/google-drive/return',
  path: '/oauth/google-drive/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMotivationHealingAudioIndexRoute =
  AuthenticatedMotivationHealingAudioIndexRouteImport.update({
    id: '/motivation/healing-audio/',
    path: '/motivation/healing-audio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotivationHealingAudioCategoryIdRoute =
  AuthenticatedMotivationHealingAudioCategoryIdRouteImport.update({
    id: '/motivation/healing-audio/$categoryId',
    path: '/motivation/healing-audio/$categoryId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksPushSchedulerRoute =
  ApiPublicHooksPushSchedulerRouteImport.update({
    id: '/api/public/hooks/push-scheduler',
    path: '/api/public/hooks/push-scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/affirmations': typeof AuthenticatedAffirmationsRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/change-email': typeof AuthenticatedChangeEmailRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/daily-exercise': typeof AuthenticatedDailyExerciseRoute
  '/flags': typeof AuthenticatedFlagsRoute
  '/healing-tools': typeof AuthenticatedHealingToolsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/letters': typeof AuthenticatedLettersRoute
  '/mood-analytics': typeof AuthenticatedMoodAnalyticsRoute
  '/pictures': typeof AuthenticatedPicturesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/questionnaire': typeof AuthenticatedQuestionnaireRoute
  '/rituals': typeof AuthenticatedRitualsRoute
  '/streak-unlock': typeof AuthenticatedStreakUnlockRoute
  '/submit-bug': typeof AuthenticatedSubmitBugRoute
  '/triggers': typeof AuthenticatedTriggersRoute
  '/wins': typeof AuthenticatedWinsRoute
  '/motivation/$topicId': typeof AuthenticatedMotivationTopicIdRoute
  '/motivation/alcohol-control': typeof AuthenticatedMotivationAlcoholControlRoute
  '/motivation/gratitude-jar': typeof AuthenticatedMotivationGratitudeJarRoute
  '/motivation/guide': typeof AuthenticatedMotivationGuideRoute
  '/motivation/journey': typeof AuthenticatedMotivationJourneyRoute
  '/motivation/meditation': typeof AuthenticatedMotivationMeditationRoute
  '/motivation/walk': typeof AuthenticatedMotivationWalkRoute
  '/motivation/worry-box': typeof AuthenticatedMotivationWorryBoxRoute
  '/api/public/drive': typeof ApiPublicDriveRoute
  '/api/public/pro-trial': typeof ApiPublicProTrialRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/motivation/': typeof AuthenticatedMotivationIndexRoute
  '/motivation/healing-audio/$categoryId': typeof AuthenticatedMotivationHealingAudioCategoryIdRoute
  '/api/public/hooks/push-scheduler': typeof ApiPublicHooksPushSchedulerRoute
  '/motivation/healing-audio/': typeof AuthenticatedMotivationHealingAudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/affirmations': typeof AuthenticatedAffirmationsRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/change-email': typeof AuthenticatedChangeEmailRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/check-in': typeof AuthenticatedCheckInRoute
  '/daily-exercise': typeof AuthenticatedDailyExerciseRoute
  '/flags': typeof AuthenticatedFlagsRoute
  '/healing-tools': typeof AuthenticatedHealingToolsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/letters': typeof AuthenticatedLettersRoute
  '/mood-analytics': typeof AuthenticatedMoodAnalyticsRoute
  '/pictures': typeof AuthenticatedPicturesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/questionnaire': typeof AuthenticatedQuestionnaireRoute
  '/rituals': typeof AuthenticatedRitualsRoute
  '/streak-unlock': typeof AuthenticatedStreakUnlockRoute
  '/submit-bug': typeof AuthenticatedSubmitBugRoute
  '/triggers': typeof AuthenticatedTriggersRoute
  '/wins': typeof AuthenticatedWinsRoute
  '/motivation/$topicId': typeof AuthenticatedMotivationTopicIdRoute
  '/motivation/alcohol-control': typeof AuthenticatedMotivationAlcoholControlRoute
  '/motivation/gratitude-jar': typeof AuthenticatedMotivationGratitudeJarRoute
  '/motivation/guide': typeof AuthenticatedMotivationGuideRoute
  '/motivation/journey': typeof AuthenticatedMotivationJourneyRoute
  '/motivation/meditation': typeof AuthenticatedMotivationMeditationRoute
  '/motivation/walk': typeof AuthenticatedMotivationWalkRoute
  '/motivation/worry-box': typeof AuthenticatedMotivationWorryBoxRoute
  '/api/public/drive': typeof ApiPublicDriveRoute
  '/api/public/pro-trial': typeof ApiPublicProTrialRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/motivation': typeof AuthenticatedMotivationIndexRoute
  '/motivation/healing-audio/$categoryId': typeof AuthenticatedMotivationHealingAudioCategoryIdRoute
  '/api/public/hooks/push-scheduler': typeof ApiPublicHooksPushSchedulerRoute
  '/motivation/healing-audio': typeof AuthenticatedMotivationHealingAudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/paywall': typeof PaywallRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/affirmations': typeof AuthenticatedAffirmationsRoute
  '/_authenticated/badges': typeof AuthenticatedBadgesRoute
  '/_authenticated/change-email': typeof AuthenticatedChangeEmailRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/check-in': typeof AuthenticatedCheckInRoute
  '/_authenticated/daily-exercise': typeof AuthenticatedDailyExerciseRoute
  '/_authenticated/flags': typeof AuthenticatedFlagsRoute
  '/_authenticated/healing-tools': typeof AuthenticatedHealingToolsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/letters': typeof AuthenticatedLettersRoute
  '/_authenticated/mood-analytics': typeof AuthenticatedMoodAnalyticsRoute
  '/_authenticated/pictures': typeof AuthenticatedPicturesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/questionnaire': typeof AuthenticatedQuestionnaireRoute
  '/_authenticated/rituals': typeof AuthenticatedRitualsRoute
  '/_authenticated/streak-unlock': typeof AuthenticatedStreakUnlockRoute
  '/_authenticated/submit-bug': typeof AuthenticatedSubmitBugRoute
  '/_authenticated/triggers': typeof AuthenticatedTriggersRoute
  '/_authenticated/wins': typeof AuthenticatedWinsRoute
  '/_authenticated/motivation/$topicId': typeof AuthenticatedMotivationTopicIdRoute
  '/_authenticated/motivation/alcohol-control': typeof AuthenticatedMotivationAlcoholControlRoute
  '/_authenticated/motivation/gratitude-jar': typeof AuthenticatedMotivationGratitudeJarRoute
  '/_authenticated/motivation/guide': typeof AuthenticatedMotivationGuideRoute
  '/_authenticated/motivation/journey': typeof AuthenticatedMotivationJourneyRoute
  '/_authenticated/motivation/meditation': typeof AuthenticatedMotivationMeditationRoute
  '/_authenticated/motivation/walk': typeof AuthenticatedMotivationWalkRoute
  '/_authenticated/motivation/worry-box': typeof AuthenticatedMotivationWorryBoxRoute
  '/api/public/drive': typeof ApiPublicDriveRoute
  '/api/public/pro-trial': typeof ApiPublicProTrialRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/_authenticated/motivation/': typeof AuthenticatedMotivationIndexRoute
  '/_authenticated/motivation/healing-audio/$categoryId': typeof AuthenticatedMotivationHealingAudioCategoryIdRoute
  '/api/public/hooks/push-scheduler': typeof ApiPublicHooksPushSchedulerRoute
  '/_authenticated/motivation/healing-audio/': typeof AuthenticatedMotivationHealingAudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/paywall'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/activity'
    | '/affirmations'
    | '/badges'
    | '/change-email'
    | '/change-password'
    | '/check-in'
    | '/daily-exercise'
    | '/flags'
    | '/healing-tools'
    | '/home'
    | '/journal'
    | '/letters'
    | '/mood-analytics'
    | '/pictures'
    | '/profile'
    | '/questionnaire'
    | '/rituals'
    | '/streak-unlock'
    | '/submit-bug'
    | '/triggers'
    | '/wins'
    | '/motivation/$topicId'
    | '/motivation/alcohol-control'
    | '/motivation/gratitude-jar'
    | '/motivation/guide'
    | '/motivation/journey'
    | '/motivation/meditation'
    | '/motivation/walk'
    | '/motivation/worry-box'
    | '/api/public/drive'
    | '/api/public/pro-trial'
    | '/oauth/google-drive/return'
    | '/motivation/'
    | '/motivation/healing-audio/$categoryId'
    | '/api/public/hooks/push-scheduler'
    | '/motivation/healing-audio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/paywall'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/activity'
    | '/affirmations'
    | '/badges'
    | '/change-email'
    | '/change-password'
    | '/check-in'
    | '/daily-exercise'
    | '/flags'
    | '/healing-tools'
    | '/home'
    | '/journal'
    | '/letters'
    | '/mood-analytics'
    | '/pictures'
    | '/profile'
    | '/questionnaire'
    | '/rituals'
    | '/streak-unlock'
    | '/submit-bug'
    | '/triggers'
    | '/wins'
    | '/motivation/$topicId'
    | '/motivation/alcohol-control'
    | '/motivation/gratitude-jar'
    | '/motivation/guide'
    | '/motivation/journey'
    | '/motivation/meditation'
    | '/motivation/walk'
    | '/motivation/worry-box'
    | '/api/public/drive'
    | '/api/public/pro-trial'
    | '/oauth/google-drive/return'
    | '/motivation'
    | '/motivation/healing-audio/$categoryId'
    | '/api/public/hooks/push-scheduler'
    | '/motivation/healing-audio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/paywall'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/activity'
    | '/_authenticated/affirmations'
    | '/_authenticated/badges'
    | '/_authenticated/change-email'
    | '/_authenticated/change-password'
    | '/_authenticated/check-in'
    | '/_authenticated/daily-exercise'
    | '/_authenticated/flags'
    | '/_authenticated/healing-tools'
    | '/_authenticated/home'
    | '/_authenticated/journal'
    | '/_authenticated/letters'
    | '/_authenticated/mood-analytics'
    | '/_authenticated/pictures'
    | '/_authenticated/profile'
    | '/_authenticated/questionnaire'
    | '/_authenticated/rituals'
    | '/_authenticated/streak-unlock'
    | '/_authenticated/submit-bug'
    | '/_authenticated/triggers'
    | '/_authenticated/wins'
    | '/_authenticated/motivation/$topicId'
    | '/_authenticated/motivation/alcohol-control'
    | '/_authenticated/motivation/gratitude-jar'
    | '/_authenticated/motivation/guide'
    | '/_authenticated/motivation/journey'
    | '/_authenticated/motivation/meditation'
    | '/_authenticated/motivation/walk'
    | '/_authenticated/motivation/worry-box'
    | '/api/public/drive'
    | '/api/public/pro-trial'
    | '/oauth/google-drive/return'
    | '/_authenticated/motivation/'
    | '/_authenticated/motivation/healing-audio/$categoryId'
    | '/api/public/hooks/push-scheduler'
    | '/_authenticated/motivation/healing-audio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PaywallRoute: typeof PaywallRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiPublicDriveRoute: typeof ApiPublicDriveRoute
  ApiPublicProTrialRoute: typeof ApiPublicProTrialRoute
  OauthGoogleDriveReturnRoute: typeof OauthGoogleDriveReturnRoute
  ApiPublicHooksPushSchedulerRoute: typeof ApiPublicHooksPushSchedulerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affirmations': {
      id: '/_authenticated/affirmations'
      path: '/affirmations'
      fullPath: '/affirmations'
      preLoaderRoute: typeof AuthenticatedAffirmationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/badges': {
      id: '/_authenticated/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AuthenticatedBadgesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-email': {
      id: '/_authenticated/change-email'
      path: '/change-email'
      fullPath: '/change-email'
      preLoaderRoute: typeof AuthenticatedChangeEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-in': {
      id: '/_authenticated/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthenticatedCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-exercise': {
      id: '/_authenticated/daily-exercise'
      path: '/daily-exercise'
      fullPath: '/daily-exercise'
      preLoaderRoute: typeof AuthenticatedDailyExerciseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flags': {
      id: '/_authenticated/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof AuthenticatedFlagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/healing-tools': {
      id: '/_authenticated/healing-tools'
      path: '/healing-tools'
      fullPath: '/healing-tools'
      preLoaderRoute: typeof AuthenticatedHealingToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/letters': {
      id: '/_authenticated/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof AuthenticatedLettersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mood-analytics': {
      id: '/_authenticated/mood-analytics'
      path: '/mood-analytics'
      fullPath: '/mood-analytics'
      preLoaderRoute: typeof AuthenticatedMoodAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pictures': {
      id: '/_authenticated/pictures'
      path: '/pictures'
      fullPath: '/pictures'
      preLoaderRoute: typeof AuthenticatedPicturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questionnaire': {
      id: '/_authenticated/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof AuthenticatedQuestionnaireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rituals': {
      id: '/_authenticated/rituals'
      path: '/rituals'
      fullPath: '/rituals'
      preLoaderRoute: typeof AuthenticatedRitualsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/streak-unlock': {
      id: '/_authenticated/streak-unlock'
      path: '/streak-unlock'
      fullPath: '/streak-unlock'
      preLoaderRoute: typeof AuthenticatedStreakUnlockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit-bug': {
      id: '/_authenticated/submit-bug'
      path: '/submit-bug'
      fullPath: '/submit-bug'
      preLoaderRoute: typeof AuthenticatedSubmitBugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/triggers': {
      id: '/_authenticated/triggers'
      path: '/triggers'
      fullPath: '/triggers'
      preLoaderRoute: typeof AuthenticatedTriggersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wins': {
      id: '/_authenticated/wins'
      path: '/wins'
      fullPath: '/wins'
      preLoaderRoute: typeof AuthenticatedWinsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivation/': {
      id: '/_authenticated/motivation/'
      path: '/motivation'
      fullPath: '/motivation/'
      preLoaderRoute: typeof AuthenticatedMotivationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivation/$topicId': {
      id: '/_authenticated/motivation/$topicId'
      path: '/motivation/$topicId'
      fullPath: '/motivation/$topicId'
      preLoaderRoute: typeof AuthenticatedMotivationTopicIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivation/alcohol-control': {
      id: '/_authenticated/motivation/alcohol-control'
      path: '/motivation/alcohol-control'
      fullPath: '/motivation/alcohol-control'
      preLoaderRoute: typeof AuthenticatedMotivationAlcoholControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivation/gratitude-jar': {
      id: '/_authenticated/motivation/gratitude-jar'
      path: '/motivation/gratitude-jar'
      fullPath: '/motivation/gratitude-jar'
      preLoaderRoute: typeof AuthenticatedMotivationGratitudeJarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivation/guide': {
      id: '/_authenticated/motivation/guide'
      path: '/motivation/guide'
      fullPath: '/motivation/guide'
      preLoaderRoute: typeof AuthenticatedMotivationGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivation/journey': {
      id: '/_authenticated/motivation/journey'
      path: '/motivation/journey'
      fullPath: '/motivation/journey'
      preLoaderRoute: typeof AuthenticatedMotivationJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivation/meditation': {
      id: '/_authenticated/motivation/meditation'
      path: '/motivation/meditation'
      fullPath: '/motivation/meditation'
      preLoaderRoute: typeof AuthenticatedMotivationMeditationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivation/walk': {
      id: '/_authenticated/motivation/walk'
      path: '/motivation/walk'
      fullPath: '/motivation/walk'
      preLoaderRoute: typeof AuthenticatedMotivationWalkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivation/worry-box': {
      id: '/_authenticated/motivation/worry-box'
      path: '/motivation/worry-box'
      fullPath: '/motivation/worry-box'
      preLoaderRoute: typeof AuthenticatedMotivationWorryBoxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/drive': {
      id: '/api/public/drive'
      path: '/api/public/drive'
      fullPath: '/api/public/drive'
      preLoaderRoute: typeof ApiPublicDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pro-trial': {
      id: '/api/public/pro-trial'
      path: '/api/public/pro-trial'
      fullPath: '/api/public/pro-trial'
      preLoaderRoute: typeof ApiPublicProTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-drive/return': {
      id: '/oauth/google-drive/return'
      path: '/oauth/google-drive/return'
      fullPath: '/oauth/google-drive/return'
      preLoaderRoute: typeof OauthGoogleDriveReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/motivation/healing-audio/': {
      id: '/_authenticated/motivation/healing-audio/'
      path: '/motivation/healing-audio'
      fullPath: '/motivation/healing-audio/'
      preLoaderRoute: typeof AuthenticatedMotivationHealingAudioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motivation/healing-audio/$categoryId': {
      id: '/_authenticated/motivation/healing-audio/$categoryId'
      path: '/motivation/healing-audio/$categoryId'
      fullPath: '/motivation/healing-audio/$categoryId'
      preLoaderRoute: typeof AuthenticatedMotivationHealingAudioCategoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/push-scheduler': {
      id: '/api/public/hooks/push-scheduler'
      path: '/api/public/hooks/push-scheduler'
      fullPath: '/api/public/hooks/push-scheduler'
      preLoaderRoute: typeof ApiPublicHooksPushSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAffirmationsRoute: typeof AuthenticatedAffirmationsRoute
  AuthenticatedBadgesRoute: typeof AuthenticatedBadgesRoute
  AuthenticatedChangeEmailRoute: typeof AuthenticatedChangeEmailRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCheckInRoute: typeof AuthenticatedCheckInRoute
  AuthenticatedDailyExerciseRoute: typeof AuthenticatedDailyExerciseRoute
  AuthenticatedFlagsRoute: typeof AuthenticatedFlagsRoute
  AuthenticatedHealingToolsRoute: typeof AuthenticatedHealingToolsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedLettersRoute: typeof AuthenticatedLettersRoute
  AuthenticatedMoodAnalyticsRoute: typeof AuthenticatedMoodAnalyticsRoute
  AuthenticatedPicturesRoute: typeof AuthenticatedPicturesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuestionnaireRoute: typeof AuthenticatedQuestionnaireRoute
  AuthenticatedRitualsRoute: typeof AuthenticatedRitualsRoute
  AuthenticatedStreakUnlockRoute: typeof AuthenticatedStreakUnlockRoute
  AuthenticatedSubmitBugRoute: typeof AuthenticatedSubmitBugRoute
  AuthenticatedTriggersRoute: typeof AuthenticatedTriggersRoute
  AuthenticatedWinsRoute: typeof AuthenticatedWinsRoute
  AuthenticatedMotivationTopicIdRoute: typeof AuthenticatedMotivationTopicIdRoute
  AuthenticatedMotivationAlcoholControlRoute: typeof AuthenticatedMotivationAlcoholControlRoute
  AuthenticatedMotivationGratitudeJarRoute: typeof AuthenticatedMotivationGratitudeJarRoute
  AuthenticatedMotivationGuideRoute: typeof AuthenticatedMotivationGuideRoute
  AuthenticatedMotivationJourneyRoute: typeof AuthenticatedMotivationJourneyRoute
  AuthenticatedMotivationMeditationRoute: typeof AuthenticatedMotivationMeditationRoute
  AuthenticatedMotivationWalkRoute: typeof AuthenticatedMotivationWalkRoute
  AuthenticatedMotivationWorryBoxRoute: typeof AuthenticatedMotivationWorryBoxRoute
  AuthenticatedMotivationIndexRoute: typeof AuthenticatedMotivationIndexRoute
  AuthenticatedMotivationHealingAudioCategoryIdRoute: typeof AuthenticatedMotivationHealingAudioCategoryIdRoute
  AuthenticatedMotivationHealingAudioIndexRoute: typeof AuthenticatedMotivationHealingAudioIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAffirmationsRoute: AuthenticatedAffirmationsRoute,
  AuthenticatedBadgesRoute: AuthenticatedBadgesRoute,
  AuthenticatedChangeEmailRoute: AuthenticatedChangeEmailRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCheckInRoute: AuthenticatedCheckInRoute,
  AuthenticatedDailyExerciseRoute: AuthenticatedDailyExerciseRoute,
  AuthenticatedFlagsRoute: AuthenticatedFlagsRoute,
  AuthenticatedHealingToolsRoute: AuthenticatedHealingToolsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedLettersRoute: AuthenticatedLettersRoute,
  AuthenticatedMoodAnalyticsRoute: AuthenticatedMoodAnalyticsRoute,
  AuthenticatedPicturesRoute: AuthenticatedPicturesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuestionnaireRoute: AuthenticatedQuestionnaireRoute,
  AuthenticatedRitualsRoute: AuthenticatedRitualsRoute,
  AuthenticatedStreakUnlockRoute: AuthenticatedStreakUnlockRoute,
  AuthenticatedSubmitBugRoute: AuthenticatedSubmitBugRoute,
  AuthenticatedTriggersRoute: AuthenticatedTriggersRoute,
  AuthenticatedWinsRoute: AuthenticatedWinsRoute,
  AuthenticatedMotivationTopicIdRoute: AuthenticatedMotivationTopicIdRoute,
  AuthenticatedMotivationAlcoholControlRoute:
    AuthenticatedMotivationAlcoholControlRoute,
  AuthenticatedMotivationGratitudeJarRoute:
    AuthenticatedMotivationGratitudeJarRoute,
  AuthenticatedMotivationGuideRoute: AuthenticatedMotivationGuideRoute,
  AuthenticatedMotivationJourneyRoute: AuthenticatedMotivationJourneyRoute,
  AuthenticatedMotivationMeditationRoute:
    AuthenticatedMotivationMeditationRoute,
  AuthenticatedMotivationWalkRoute: AuthenticatedMotivationWalkRoute,
  AuthenticatedMotivationWorryBoxRoute: AuthenticatedMotivationWorryBoxRoute,
  AuthenticatedMotivationIndexRoute: AuthenticatedMotivationIndexRoute,
  AuthenticatedMotivationHealingAudioCategoryIdRoute:
    AuthenticatedMotivationHealingAudioCategoryIdRoute,
  AuthenticatedMotivationHealingAudioIndexRoute:
    AuthenticatedMotivationHealingAudioIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PaywallRoute: PaywallRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiPublicDriveRoute: ApiPublicDriveRoute,
  ApiPublicProTrialRoute: ApiPublicProTrialRoute,
  OauthGoogleDriveReturnRoute: OauthGoogleDriveReturnRoute,
  ApiPublicHooksPushSchedulerRoute: ApiPublicHooksPushSchedulerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
